name: tavern
author: Patrick Laub <pajamallama@google.com>
url: https://github.com/tapted/tavern
dependencies:
  chrome_gen: any
  path: any
  js: any
  stack_trace: any
  analyzer: any
  crypto: any
  collection_helpers: any
  yaml: any
  source_maps: any
  watcher: any
  oauth2: any